<?php

/**
 * @file
 * Created by IntelliJ IDEA.
 */

/**
 * Implements hook_menu().
 */
function date_serial_menu() {
  $items = array();
  $items['admin/config/dateserial'] = array(
    'title' => 'Auto ID configuration',
    'access arguments' => array('administer site configuration'),
    'position' => 'left',
    'weight' => -100,
    'page callback' => 'system_admin_menu_block_page',
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/dateserial/create'] = array(
    'title' => 'Create new ID schema',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('date_serial_create_schema_form'),
    'file' => 'date_serial.config.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/dateserial/edit'] = array(
    'title' => 'Manage existing schema',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('date_serial_edit_schema_form'),
    'file' => 'date_serial.config.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}
